app3.proyecto=Spring Boot Project Demo 3
app3.objetivo1=Conocer las diferentes alternativas para crear y acceder a los par�metros definidos en los ficheros .properties
app3.objetivo2=Comprender la utilidad de capturar y sobrecargar el evento de inicio de la aplicaci�n.
app3.objetivo3=Entender las ventajas de explotar la memoria de aplicaci�n (atributos static).
app3.ide=Sprint Tool Suite, versi�n: 5
app3.servidor=Apache Tomcat, versi�n: 11
app3.jdk=OpenJdk, versi�n: 21
app3.gestorproyecto=Maven, versi�n: 4
app3.dependencias=Spring, versi�n 4.1.*. M�dulos: spring-boot-starter-web, spring-boot-starter-tomcat, tomcat-embed-jasper, tomcat-embed-jasper
